nomad/shenzhen

lib/shenzhen/plugins/hockeyapp.rb
In multiple support discussions, HockeyApp has recommended using http://upload.hockeyapp.net instead of http://rink.hockeyapp.net:
* http://support.hockeyapp.net/discussions/problems/23558-360mb-ipa-download-very-slow
* http://support.hockeyapp.net/discussions/problems/32813-slow-upload-times
From my testing using `curl`, the upload of large files has been at least 25% faster.
=> Switch API to upload.hockeyapp.net

lib/shenzhen/plugins/itunesconnect.rb
Hey @mattt, sorry to bother you again with another pull request!
I have switched to storing the password in the keychain, instead of passing it every time as a command line parameter. I've noticed this is not working, because it's passing down an instance of GenericPassword instead of the password itself.
=> Pass down the password instead of the GenericPassword instance

lib/shenzhen/plugins/itunesconnect.rb
iTunes Connect password supplied via environment variable or command argument appears to be broken:
private method `password' called for "<password>":String
I think this code implements the behaviour that was actually intended in commit 585ca00, but I'm unsure.
=> Fixed error with iTunesConnect password

lib/shenzhen/plugins/hockeyapp.rb
We're trying to streamline our automated build pipeline at work using HockeyApp and Shenzhen, but we'd like to be able to explicitly send out separate builds to separate teams. Hopefully this pull request will do the trick. :)
Thanks again for creating Shenzhen!
=> Added 'teams' and 'users' parameters to HockeyApp.

lib/shenzhen/commands/build.rb
This addresses issue #182, and improves interoperability with other projects that might have expectations about what the .ipa is called.
=> Adds command option to specify generated .ipa filename

lib/shenzhen/commands/build.rb
The absolute path is the last line displayed, which makes it easier for other tools (thinking about [fastlane](http://fastlane.tools) to parse the path to the generated ipa file. 
If anybody finds a better way to pass the path to the generated ipa (e.g. using environment variables), let me know.
=> Path to generated ipa file is last output

lib/shenzhen/plugins/itunesconnect.rb
=> Save ipas with underscores instead of spaces

lib/shenzhen/commands/build.rb
This will output the generated `xcodebuild` command before actually running it.
Many submitted GitHub issues are related to build problems: https://github.com/nomad/shenzhen/issues/204, https://github.com/nomad/shenzhen/issues/176 and many more.
First of all, it makes it clear that `shenzhen` uses `xcodebuild` to build the app. Secondly the user can modify the generated build command (e.g. replacing `xcodebuild` with `xctool`, which is what I do if there is a build error)
Example output:
```
(master) $ ipa build
xcodebuild  Moto Deals.xcworkspace
xcodebuild -sdk iphoneos -workspace "App.xcworkspace" -scheme "Debug" -configuration 'Release' clean build archive 1> /dev/null
....
```
=> Added output of generated xcodebuild command

lib/shenzhen/plugins/crashlytics.rb
Previously if the passed in ipa_path had a space, this would fail.
=> Fixed bug when passing a path with spaces to the Crashlytics plugin

lib/shenzhen/plugins/crashlytics.rb
Useful for CI if don't want to spam users every time a new build is available.
http://support.crashlytics.com/knowledgebase/articles/370383-beta-distribution-with-ios-build-servers
=> Added support for setting the notifications flag for crashlytics

lib/shenzhen/plugins/itunesconnect.rb
Xcode 6.3 moved the path to the iTMSTransporter. This tries to use the original path and uses the new one if the file doesn't exist.
This addresses #243.
=> Use new path to iTMSTransporter when needed

lib/shenzhen/plugins/itunesconnect.rb
This should be added in addition to #245 . We look for the exit status of the transporter command and raise an error when it returns a non-zero exit code.
This would have allowed us to pin point where the failure was much faster when our builds stopped making it to iTunes Connect.
=> Fail loudly when the transporter returns a non-zero exit code.

lib/shenzhen/commands/build.rb
If you attempt to submit an .ipa built using shenzhen that contains a WatchKit app the upload will succeed but you'll receive an error email from iTunes with this message:
Invalid WatchKit Support - The bundle contains an invalid implementation of WatchKit. The app may have been built or signed with non-compliant or pre-release tools. Visit developer.apple.com for more information.
This stackoverflow answer explains how to fix it:
http://stackoverflow.com/a/29400301/2418382
This pull request adds the necessary WatchKitSupport folder and WK binary so that the .ipa is valid.
=> Adding WatchKitSupport folder to zipped .ipa for WatchKit apps

lib/shenzhen/xcodebuild.rb
I work in an environment where I have to test and build against multiple Xcode versions. I use a combination of `xcode-select`, `xcrun`, and `DEVELOPER_DIR` to control the active Xcode.
Rather than using `sudo xcode-select` to force a particular Xcode version (in CI environments for example) I use:
```
$ DEVELOPER_DIR=/path/to/Xcode.app/Contents/Developer xcrun xcodebuild
```
I would like to be able to use this gem in a similar way:
```
$ DEVELOPER_DIR=/path/to/Xcode.app/Contents/Developer ipa
```
* `$ man xcode-select`
* `$ man xcrun`
=> Call xcodebuild in the context of xcrun

shenzhen.gemspec
The current release of dotenv is 2.0.1 (April 3 2015).
I am a new user, so I don't yet know how dotenv is used in this project.  I cannot say for sure how this change will affect this gem's behavior.   It is not clear to me that dotenv is even used in this project; I don't see a call to Dotenv.load.
The ~> 0.7 conflicts with a couple of other gems I use.
=> Allow dotenv >= 0.7

lib/shenzhen/plugins/crashlytics.rb
`File.exists?` is deprecated in favor of `File.exist?`
=> Migrate to new code standard

shenzhen.gemspec
This makes the gem installable together with the pilot tool from @krausefx
=> Update Faraday dependency to 0.9

lib/shenzhen/plugins/testfairy.rb
The parameter name for TestFairy testers groups was mismatched.
It "tester-groups" rather than "testers-groups".
=> FIX: Fixed bad parameter for TestFairy testers groups

lib/shenzhen/commands/info.rb
This fixes issue #271 with .app-files containing spaces.
The search path needs to be quoted since the spaces are not escaped otherwise.
=> Fixed issue with search path containing spaces to security command

lib/shenzhen/plugins/s3.rb
I couldn't upload artifacts containing spaces in their path without escaping.
=> Escape arguments for system call

lib/shenzhen/commands/build.rb
I did not see a contributor's guide, so please let me know if there are any changes needed to this work. 
Thanks!
=> Build command: update Xcode version validation for Xcode 10+ (#351)
